//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazWeb.ServicioCatalogo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCatalogo.IServicioCatalogo")]
    public interface IServicioCatalogo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCatalogo/FindAll", ReplyAction="http://tempuri.org/IServicioCatalogo/FindAllResponse")]
        EntidadesNegocio.Servicio[] FindAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCatalogo/FindAll", ReplyAction="http://tempuri.org/IServicioCatalogo/FindAllResponse")]
        System.Threading.Tasks.Task<EntidadesNegocio.Servicio[]> FindAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCatalogoChannel : InterfazWeb.ServicioCatalogo.IServicioCatalogo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCatalogoClient : System.ServiceModel.ClientBase<InterfazWeb.ServicioCatalogo.IServicioCatalogo>, InterfazWeb.ServicioCatalogo.IServicioCatalogo {
        
        public ServicioCatalogoClient() {
        }
        
        public ServicioCatalogoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCatalogoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCatalogoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCatalogoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EntidadesNegocio.Servicio[] FindAll() {
            return base.Channel.FindAll();
        }
        
        public System.Threading.Tasks.Task<EntidadesNegocio.Servicio[]> FindAllAsync() {
            return base.Channel.FindAllAsync();
        }
    }
}
