//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazWeb.ServicioFileProveedores {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioFileProveedores.IServicioFileProveedores")]
    public interface IServicioFileProveedores {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFileProveedores/ProveedoresFile", ReplyAction="http://tempuri.org/IServicioFileProveedores/ProveedoresFileResponse")]
        bool ProveedoresFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFileProveedores/ProveedoresFile", ReplyAction="http://tempuri.org/IServicioFileProveedores/ProveedoresFileResponse")]
        System.Threading.Tasks.Task<bool> ProveedoresFileAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioFileProveedoresChannel : InterfazWeb.ServicioFileProveedores.IServicioFileProveedores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFileProveedoresClient : System.ServiceModel.ClientBase<InterfazWeb.ServicioFileProveedores.IServicioFileProveedores>, InterfazWeb.ServicioFileProveedores.IServicioFileProveedores {
        
        public ServicioFileProveedoresClient() {
        }
        
        public ServicioFileProveedoresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFileProveedoresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFileProveedoresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFileProveedoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ProveedoresFile() {
            return base.Channel.ProveedoresFile();
        }
        
        public System.Threading.Tasks.Task<bool> ProveedoresFileAsync() {
            return base.Channel.ProveedoresFileAsync();
        }
    }
}
