//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazWeb.ServicioDesactivarProveedor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioDesactivarProveedor.IServicioDesactivarProveedor")]
    public interface IServicioDesactivarProveedor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDesactivarProveedor/DesactivarProveedor", ReplyAction="http://tempuri.org/IServicioDesactivarProveedor/DesactivarProveedorResponse")]
        bool DesactivarProveedor(string rut, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDesactivarProveedor/DesactivarProveedor", ReplyAction="http://tempuri.org/IServicioDesactivarProveedor/DesactivarProveedorResponse")]
        System.Threading.Tasks.Task<bool> DesactivarProveedorAsync(string rut, bool activo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioDesactivarProveedorChannel : InterfazWeb.ServicioDesactivarProveedor.IServicioDesactivarProveedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDesactivarProveedorClient : System.ServiceModel.ClientBase<InterfazWeb.ServicioDesactivarProveedor.IServicioDesactivarProveedor>, InterfazWeb.ServicioDesactivarProveedor.IServicioDesactivarProveedor {
        
        public ServicioDesactivarProveedorClient() {
        }
        
        public ServicioDesactivarProveedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDesactivarProveedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDesactivarProveedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDesactivarProveedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DesactivarProveedor(string rut, bool activo) {
            return base.Channel.DesactivarProveedor(rut, activo);
        }
        
        public System.Threading.Tasks.Task<bool> DesactivarProveedorAsync(string rut, bool activo) {
            return base.Channel.DesactivarProveedorAsync(rut, activo);
        }
    }
}
