//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazWeb.ServicioNuevoProv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioNuevoProv.IServicioNuevoProv")]
    public interface IServicioNuevoProv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNuevoProv/NuevoProveedor", ReplyAction="http://tempuri.org/IServicioNuevoProv/NuevoProveedorResponse")]
        bool NuevoProveedor(string rut, string clave, string nombre, string email, string telefono, bool vip, int[] servicios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNuevoProv/NuevoProveedor", ReplyAction="http://tempuri.org/IServicioNuevoProv/NuevoProveedorResponse")]
        System.Threading.Tasks.Task<bool> NuevoProveedorAsync(string rut, string clave, string nombre, string email, string telefono, bool vip, int[] servicios);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioNuevoProvChannel : InterfazWeb.ServicioNuevoProv.IServicioNuevoProv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioNuevoProvClient : System.ServiceModel.ClientBase<InterfazWeb.ServicioNuevoProv.IServicioNuevoProv>, InterfazWeb.ServicioNuevoProv.IServicioNuevoProv {
        
        public ServicioNuevoProvClient() {
        }
        
        public ServicioNuevoProvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioNuevoProvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNuevoProvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNuevoProvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool NuevoProveedor(string rut, string clave, string nombre, string email, string telefono, bool vip, int[] servicios) {
            return base.Channel.NuevoProveedor(rut, clave, nombre, email, telefono, vip, servicios);
        }
        
        public System.Threading.Tasks.Task<bool> NuevoProveedorAsync(string rut, string clave, string nombre, string email, string telefono, bool vip, int[] servicios) {
            return base.Channel.NuevoProveedorAsync(rut, clave, nombre, email, telefono, vip, servicios);
        }
    }
}
