//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazWeb.ServicioServiciosFile {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioServiciosFile.IServicioServiciosFile")]
    public interface IServicioServiciosFile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioServiciosFile/ServiciosFile", ReplyAction="http://tempuri.org/IServicioServiciosFile/ServiciosFileResponse")]
        bool ServiciosFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioServiciosFile/ServiciosFile", ReplyAction="http://tempuri.org/IServicioServiciosFile/ServiciosFileResponse")]
        System.Threading.Tasks.Task<bool> ServiciosFileAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioServiciosFileChannel : InterfazWeb.ServicioServiciosFile.IServicioServiciosFile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioServiciosFileClient : System.ServiceModel.ClientBase<InterfazWeb.ServicioServiciosFile.IServicioServiciosFile>, InterfazWeb.ServicioServiciosFile.IServicioServiciosFile {
        
        public ServicioServiciosFileClient() {
        }
        
        public ServicioServiciosFileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioServiciosFileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioServiciosFileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioServiciosFileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ServiciosFile() {
            return base.Channel.ServiciosFile();
        }
        
        public System.Threading.Tasks.Task<bool> ServiciosFileAsync() {
            return base.Channel.ServiciosFileAsync();
        }
    }
}
